object Dependencies {
    const val CORE = "androidx.core:core-ktx:${Versions.CORE_VER}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${Versions.APPCOMPAT_VER}"
    const val MATERIAL = "com.google.android.material:material:${Versions.MATERIAL_VER}"
    const val CONSTRAINT = "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT_VER}"
    const val COROUTINES_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.COROUTINES_CORE_VER}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.COROUTINES_CORE_VER}"
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.LIFECYCLE_VIEWMODEL_VER}"
    const val COROUTINES_RETROFIT_ADAPTER = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:${Versions.COROUTINES_RETROFIT_ADAPTER_VER}"
    const val KOIN = "io.insert-koin:koin-android:${Versions.KOIN_VER}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT_VER}"
    const val RETROFIT_GSON = "com.squareup.retrofit2:converter-gson:${Versions.RETROFIT_VER}"
    const val LEANBACK = "androidx.leanback:leanback:${Versions.LEANBACK_VER}"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${Versions.NAVIGATION_FRAGMENT_VER}"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${Versions.NAVIGATION_FRAGMENT_VER}"
    const val NAVIGATION_DYNAMIC = "androidx.navigation:navigation-dynamic-features-fragment:${Versions.NAVIGATION_FRAGMENT_VER}"
    const val GLIDE = "com.github.bumptech.glide:glide:${Versions.GLIDE_VER}"
    const val LOTTIE = "com.airbnb.android:lottie:${Versions.LOTTIE_VER}"
}
object Versions {
    const val CORE_VER = "1.7.0"
    const val APPCOMPAT_VER = "1.4.1"
    const val MATERIAL_VER = "1.5.0"
    const val CONSTRAINT_VER = "2.1.3"
    const val COROUTINES_CORE_VER = "1.6.1"
    const val LIFECYCLE_VIEWMODEL_VER = "2.4.1"
    const val COROUTINES_RETROFIT_ADAPTER_VER = "0.9.2"
    const val KOIN_VER = "3.1.6"
    const val RETROFIT_VER = "2.9.0"
    const val LEANBACK_VER = "1.0.0"
    const val NAVIGATION_FRAGMENT_VER: String = "2.5.1"
    const val GLIDE_VER = "4.14.2"
    const val LOTTIE_VER = "3.4.4"
}
